# Generated by Django 5.0.14 on 2025-09-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile'),
        ('myapp', '000X_create_role_groups'),
    ]

    operations = [
    ]
