# Generated by Django 5.0.14 on 2025-09-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_merge_0002_userprofile_000X_create_role_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Certificates_Documents', 'Certificates & Documents'), ('Finance_Admin', 'Finance & Admin'), ('IT_Support', 'IT Support'), ('Courses_Training', 'Courses & Training'), ('Facilities_Logistics', 'Facilities & Logistics')], max_length=32)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=32)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=32)),
                ('created_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'complaints',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('warden', 'Warden'), ('rector', 'Rector'), ('maintenance', 'Maintenance'), ('it', 'IT'), ('panel', 'Panel')], default='student', max_length=20),
        ),
    ]
