# Generated by Django 5.1.5 on 2025-09-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_complaint_alter_userprofile_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "students",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="student_db_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
